import type { MedalConfig } from './types';

export const defaultConfig: MedalConfig = {
  shape: 'circle',
  diameter: 72,
  width: 72,
  height: 72,
  thickness: 5,
  edgeBevel: 1,
  cornerRadius: 8,
  polygonSides: 6,
  quality: 144,
  materialPreset: 'gold',
  color: '#d9a441',
  metalness: 0.95,
  roughness: 0.28,
  reliefDepth: 0.45,
  reliefScale: 52,
  reliefRotation: 0,
  reliefOffsetX: 0,
  reliefOffsetY: 0,
  reliefColor: '#f6d45f',
  reliefMetalness: 0.92,
  reliefRoughness: 0.24,
  backText: '',
  backTextSize: 3.2,
  backMarkDepth: 0.35,
  backTextOffsetY: 5,
  backLogoEnabled: true,
  backLogoWidth: 8,
  backLogoOffsetY: -7,
  backMarkColor: '#ffffff'
};
